export const userStyle = {
    container : {
        backgroundColor: 'rgb(255, 255, 255)',
        color: 'rgb(97, 97, 97)',
        // transition: 'boxShadow 300ms cubic-bezier(0.4, 0, 0.2, 1) 0ms',
        boxShadow: 'none',
        borderRadius: '12px',
        overflow: 'hidden',
        // border: '1px solid rgba(144, 202, 249, 0.46)',
        height: 'max-content',
        padding:'30px',
    },
    sub_container : {
        bgcolor: '#fff',
        height: 'auto',
        borderLeft: '0px', 
        padding: '20px',
        borderRight: '0px', 
        borderBottom: '0px', 
        borderRadius: '5px', 
        boxShadow: '6px 6px 6px 9px #dedbdbae', 
        marginTop: '50px',
    },
    button_add: {
        backgroundColor: '#7009AB !important',
        color: 'white',
        textTransform: 'Capitalize',
        marginRight: '5px !important',
        height: '40px !important',
        padding: '10px !important',
        fontWeight: '600 !important',
        borderRadius: '7px !important',
        float: 'right !important',
        border: '0px !important',
        '&:hover': {
            backgroundColor: '#9F3ED7 !important',
        }
    },
    button_grp : {
        backgroundColor: 'rgb(245 243 246) !important',
        color: '#7009AB !important',
        borderColor: '#ddd !important',
        margin: '1px !important',
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'center',
        fontSize: '12px !important',
    },
    UnitHeaderText:{
        fontFamily:"'Source Sans Pro','Helvetica Neue',Helvetica,Arial,sans-serif",
        fontSize: "23px",
        fontWeight: "400",
        margin:"10px 0px 10px 0px",
        color: 'rgb(94, 53, 177) !important',
    },
    UnitSubHeaderText:{
        fontSize: "15px",
        display: "inline-block",
        paddingLeft: "4px",
        fontWeight: "300",
        lineHeight: "1",
        color: 'rgb(94, 53, 177) !important',
    },
    button_edit : {
        backgroundColor: '#1572e8 !important',
        borderColor: '#1367d1 !important',
        color: '#fff !important',
        margin: '1px !important',
        marginRight: '5px !important',
        alignItems: 'center !important',
        textAlign: 'center !important',
        justifyContent: 'center !important',
        height: '30px !important',
        fontSize: '12px !important',
        fontWeight: '750 !important',
    },
    button_view : {
        background: '#11cdef !important',
        borderColor: '#0fb9d8 !important',
        color: '#fff !important',
        margin: '1px !important',
        marginRight: '5px !important',
        alignItems: 'center !important',
        textAlign: 'center !important',
        justifyContent: 'center !important',
        height: '30px !important',
        fontSize: '12px !important',
        fontWeight: '750 !important',
    },
    button_delete : {
        background: '#f5365c !important',
        borderColor: '#f41e48 !important',
        color: '#fff !important',
        margin: '1px !important',
        marginRight: '5px !important',
        alignItems: 'center !important',
        textAlign: 'center !important',
        justifyContent: 'center !important',
        height: '30px !important',
        fontSize: '12px !important',
        fontWeight: '750 !important',
    },
    grid_container : {
        marginTop: '50px', 
        marginBottom: '20px',
        justifyContent: 'center',
    },
}