export const userStyle = {
    container : {
        backgroundColor: 'rgb(255, 255, 255)',
        color: 'rgb(97, 97, 97)',
        boxShadow: 'none',
        borderRadius: '12px',
        overflow: 'hidden',
        height: 'max-content',
        padding:'30px',
        '& .MuiTable-root':{
            borderBottom: 'none !important',
            paddingTop: '20px',
            paddingBottom: '20px',
        },
        '& .MuiTableCell-root':{
            fontSize: '18px',
        },
        '& .MuiOutlinedInput-notchedOutline': {
            border: '1px solid #B97DF0',
        },
    },
    spanIconTax : {
        fontSize: '16px',
        paddingTop: '5px !important',
        paddingLeft: '11px',
        paddingRight: '1px',
        margin: 'auto',
        border: '1px solid #B97DF0',
        width: '45px !important',
        height: '40px',
        borderRadius: '2px',
        backgroundColor: 'white',
        color: '#7009AB' ,
    },

    buttonadd: {
        backgroundColor: '#7009ab !important',
        color: 'white',
        textTransform: 'Capitalize',
        marginRight: '5px !important',
        height: '40px !important',
        padding: '10px !important',
        fontWeight: '600 !important',
        borderRadius: '7px !important',
        float: 'right !important',
        border: '0px !important',
        '&:hover': {
            backgroundColor: '#9f3ed7 !important',
        }
    },
    gridcontainer : {
        marginTop: '50px', 
        marginBottom: '20px',
        justifyContent: 'center',
    },
    buttongrp : {
        backgroundColor: 'rgb(245 243 246) !important',
        color: '#7009AB !important',
        borderColor: '#ddd !important',
        margin: '1px !important',
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'center',
        fontSize: '12px !important',
    },
    HeaderText:{
        fontFamily:"'Source Sans Pro','Helvetica Neue',Helvetica,Arial,sans-serif",
        fontSize: "23px",
        fontWeight: "400",
        margin:"10px 0px 10px 0px",
        color: 'rgb(94, 53, 177) !important',
    },
    SubHeaderText:{
        fontSize: "15px",
        display: "inline-block",
        paddingLeft: "4px",
        fontWeight: "300",
        lineHeight: "1",
        color: 'rgb(94, 53, 177) !important',
    },
    buttonedit : {
        backgroundColor: '#1572e8 !important',
        borderColor: '#1367d1 !important',
        color: '#fff !important',
        margin: '1px !important',
        marginRight: '5px !important',
        alignItems: 'center !important',
        textAlign: 'center !important',
        justifyContent: 'center !important',
        height: '30px !important',
        fontSize: '12px !important',
        fontWeight: '750 !important',
    },
    buttonview : {
        background: '#11cdef !important',
        borderColor: '#0fb9d8 !important',
        color: '#fff !important',
        margin: '1px !important',
        marginRight: '5px !important',
        alignItems: 'center !important',
        textAlign: 'center !important',
        justifyContent: 'center !important',
        height: '30px !important',
        fontSize: '12px !important',
        fontWeight: '750 !important',
    },
    buttondelete : {
        background: '#f5365c !important',
        borderColor: '#f41e48 !important',
        color: '#fff !important',
        margin: '1px !important',
        marginRight: '5px !important',
        alignItems: 'center !important',
        textAlign: 'center !important',
        justifyContent: 'center !important',
        height: '30px !important',
        fontSize: '12px !important',
        fontWeight: '750 !important',
    }, 
    buttonmore: {
        marginTop: '20px',
        marginBottom: '20px',
        justifyContent: 'center'
    },
    spanIcons : {
        fontSize: '16px', 
        paddingTop: '5px !important', 
        paddingLeft: '7px',
        paddingRight: '0px',
        margin: 'auto', 
        border: '1px solid #b97df0', 
        width: '45px !important', 
        height: '40px', 
        borderRadius: '2px', 
        backgroundColor: 'white', 
        color: '#7009ab' ,
    },
    spanIconTax : {
        fontSize: '16px', 
        paddingTop: '5px !important', 
        paddingLeft: '11px',
        paddingRight: '1px',
        margin: 'auto', 
        border: '1px solid #b97df0', 
        width: '45px !important', 
        height: '40px', 
        borderRadius: '2px', 
        backgroundColor: 'white', 
        color: '#7009ab' ,
    },
    uploadBtn : {
        color: 'white',
        border:'1px solid #b97df0 !important',
        borderRadius: '7px !important',
        backgroundColor: '#7009ab ',
        width: '159px !important',
        fontSize: '13px !important',
        fontWeight: '600 !important',
            '&:hover' : {
                backgroundColor: 'white ',
                color: '#7009ab ',
            },
    },
    reportTableBoldtxt:{
        display:'flex',
        fontWeight:'bolder',
    },
    reportTabletxt:{
        color:'##777',
    },
    footerStyle:{
        fontSize:'16px !important',
        fontWeight:'600 !important',
        textAlign:'center !important'
    },
    footerSmlTxtStyle:{
        fontSize:'16  !important',
        fontWeight:'500 !important',
    },    
    // create page table style(green)
    tableHead1 : {
        fontWeight:'bold !important',
        fontSize:'15px',
        background:'#5CB85C !important',
        color:'white',
    },
    // Import 
    importheadtext:{
        fontSize:'20px !important',
        color: 'rgb(94, 53, 177) !important',
    },
    importsubheadtext:{
        margin:'0',
    },
    // pos create
    buttonpaid : {
        backgroundColor: '#98D973 !important',
        color: '#fff !important',
        height: '25px !important',
    },
    
}